<?php

namespace App\Controller;

use App\Entity\PageVisit;
use App\Entity\User;
use App\Form\AccountType;
use App\Form\BackgroundImagesType;
use App\Form\PasswordChangeType;
use App\Form\ProfileImageType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

class AccountController extends AbstractController
{
    private $encoder;

    public function __construct(UserPasswordEncoderInterface $encoder)
    {
        $this->encoder = $encoder;
    }
    /**
     * @Route("/UserSettings", name="accountSettings")
     */
    public function AccountTools(EntityManagerInterface $em, Request $request)
    {
        $user = $this->getUser();
        $form = $this->createForm(AccountType::class, $user);
        $form->handleRequest($request);

        $formProfImages = $this->createForm(ProfileImageType::class);
        $formProfImages->handleRequest($request);
        if ($formProfImages->isSubmitted() && $formProfImages->isValid()) {
            $data = $formProfImages->getData();
            $ProfileImage = $formProfImages->get('ProfileImage')->getData();
            if (isset($ProfileImage)) {
                $fileNameProfile = $this->generateUniqueFileName() . $ProfileImage->guessExtension();
                $file = new Filesystem();
                $fileName = $user->getProfileImage();
                if (isset($fileName) && !empty($fileName) && $fileName != NULL) {
                    try {
                        $file->remove($this->getParameter('profile_directory') . DIRECTORY_SEPARATOR . $fileName);
                    } catch (FileException $e) {
                        // ... handle exception if something happens during file upload
                    }
                }
                try {
                    $ProfileImage->move(
                        $this->getParameter('profile_directory'),
                        $fileNameProfile
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $user->setProfileImage($fileNameProfile);
                $em->persist($user);
                $em->flush();

                return $this->redirectToRoute('accountSettings');
            }
        }
        if ( $form->isSubmitted() ) {
            $data = $form->getData();
            $user->setEmail($data->getEmail());
            $user->setFirstname($data->getFirstname());
            $user->setLastname($data->getLastname());
            $user->setMobile($data->getMobile());
            $user->setDescription($data->getDescription());
            $em->persist($user);
            $em->flush();
            return $this->redirectToRoute('accountSettings');
        }

        return $this->render('Accounts/AccountSettings.html.twig', [
            'AccountData' => $user,
            'Account' => $form->createView(),
            'ImagesProf' => $formProfImages->createView(),
            'Title'=> "Admin Tools"
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * @Route("/PasswordChanger", name="PasswordChanger")
     */
    public function PasswordChanger(EntityManagerInterface $em, Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->getUser();
        if ( isset($_POST['current']) && $passwordEncoder->isPasswordValid($user, $_POST['current'])){
            $currentPassword = true;
        }else{
            $currentPassword = false;
        }
        $form = $this->createForm(PasswordChangeType::class, $user);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $currentPassword ) {
            $data=$form->getData();
            $checkPass = $passwordEncoder->encodePassword($user, $data->getPassword());
            $user->setPassword($checkPass);
            $em = $this->getDoctrine()->getManager();
            $em->flush();
            return $this->redirectToRoute('accountSettings');

        }

        return $this->render('Accounts/PasswordChange.html.twig', [
            'Password' => $form->createView(),
            'Title'=> "Change Password"
        ]);
    }
    /**
     * @Route("/Usertrace/Tracker", name="User_Tracker")
     * @Method("POST")
     */
    public function UserTracker(EntityManagerInterface $em, Request $request)
    {
        $UserID = $request->get('UserID');
        $Link = $request->get('Link');
        $User = $this->getDoctrine()->getRepository(User::class)->find($UserID);

        $pageVisit = new PageVisit();
        $pageVisit->setUser($User);
        $pageVisit->setCurrentUrl($Link);
        $pageVisit->setTime(new \DateTime());

        $em->persist($pageVisit);
        $em->flush();
        return new Response(
            json_encode("Uploaded". $User->getId().$User->getFirstname().$Link)
        );
    }


    /**
     * @Route("/email")
     */
    public function sendEmail(MailerInterface $mailer)
    {
        $email = (new Email())
            ->from('hello@example.com')
            ->to('timsplinter@live.nl')
            ->priority(Email::PRIORITY_HIGH)
            ->subject('Time for Symfony Mailer!')
            ->text('Sending emails is fun again!')
            ->html('<p>See Twig integration for better HTML integration!</p>');

        $mailer->send($email);
        return $this->redirectToRoute('app_login');

    }
}
