<?php

namespace App\Controller;

use App\Entity\Member;
use App\Entity\User;
use App\Form\MemberType;
use App\Form\ProfileImageType;
use App\Form\RegisterType;
use App\Form\UserChangeType;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Flex\Response;

class MemberManagementController extends AbstractController
{

    /**
     * @Route("/admin/Change-Member-Info/{MemberId}", name="Member-Change")
     */
    public function ChangeMember($MemberId,EntityManagerInterface $em, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $Member = $em->getRepository('App\Entity\User')->find($MemberId);


        $form = $this->createForm(UserChangeType::class, $Member);
        $form->handleRequest($request);
        if ($form->isSubmitted() ) {
            $data = $form->getData();
            $Member->setEmail($data->getEmail());
            $Member->setFirstname($data->getFirstname());
            $Member->setLastname($data->getLastname());
            $Member->setMobile($data->getMobile());
            $Member->setDescription($data->getDescription());
            $em->persist($Member);
            $em->flush();
            if ($form->get('OpenList')->isClicked()) {
                return $this->redirectToRoute('Members');
            }elseif ($form->get('StayOn')->isClicked()){
                return $this->redirectToRoute('Member-Change', array('MemberId' => $MemberId));
            } else {
                return $this->redirectToRoute('Member-Registry');
            }
        }

        $formProfImages = $this->createForm(ProfileImageType::class);
        $formProfImages->handleRequest($request);
        if ($formProfImages->isSubmitted() && $formProfImages->isValid()) {
            $data = $formProfImages->getData();
            $ProfileImage = $formProfImages->get('ProfileImage')->getData();
            if (isset($ProfileImage)) {
                $fileNameProfile = $this->generateUniqueFileName() . $ProfileImage->guessExtension();

                try {
                    $ProfileImage->move(
                        $this->getParameter('profile_directory'),
                        $fileNameProfile
                    );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
                $Member->setProfileImage($fileNameProfile);
                $em->persist($Member);
                $em->flush();
            }
        }

        return $this->render('Member/MemberRegistry.html.twig', [
            'Member' => $form->createView(),
            'AccountData' => $Member,
            'ImagesProf' => $formProfImages->createView(),
            'Title'=> "Change Existing Member"
        ]);
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }


    /**
     * @Route("/Register-admin", name="new-member-Registry")
     */
    public function Register(EntityManagerInterface $em, Request $request,AuthenticationUtils $authenticationUtils): \Symfony\Component\HttpFoundation\Response
    {

        $form = $this->createForm(RegisterType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data=$form->getData();
            $User = new User();
            $User->setUsername($data->getUsername());
            $User->setEmail($data->getEmail());
            $checkPass = $this->encoder->encodePassword($User, $data->getPassword());
            $User->setPassword($checkPass);
            $User->setFirstname($data->getFirstname());
            $User->setLastname($data->getLastname());
            $User->setActivateUser(false);
            $User->setPayed(false);
            $User->setWinterMember(false);
            $User->setSummerMember(false);
            $em->persist($User);
            $em->flush();
            return $this->redirectToRoute('app_login');
        }

        return $this->render('security/register.html.twig', [
            'controller_name' => 'CourtReservationController',
            'UserReg'=>$form->createView(),
            'imgnumber' => rand(1, 3)
        ]);
    }

    /**
     * @Route("/admin/Delete-Member-Info/{MemberId}", name="Member-Delete")
     */
    public function DeleteMember($MemberId,EntityManagerInterface $em, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $Member = $em->getRepository('App\Entity\User')->find($MemberId);


        $em= $this->getDoctrine()->getManager();
        $em->remove($Member);
        $em->flush();
        return $this->redirectToRoute('Members');
    }

    /**
     * @Route("/admin/Members", name="Members")
     */
    public function ListedMember()
    {
        $Member = $this->getDoctrine()->getRepository(User::class)->findAll();

        return $this->render('Member/ShowAllMember.html.twig', [
            'Members' => $Member,
            'Title'=> "Members"
        ]);


    }

    /**
     * @Route("/admin/check/payment", name="Payment")
     */
    public function changepayed(EntityManagerInterface $em,Request $request)
    {

        $id = $request->get('id');
        $User = $this->getDoctrine()->getRepository(User::class)->find($id);
        if ($User->getPayed()){
            $User->setPayed(false);
        }else {
            $User->setPayed(true);
        }
        $em->persist($User);
        $em->flush();
        return new \Symfony\Component\HttpFoundation\Response(
            json_encode($User->getPayed())
        );
    }
    /**
     * @Route("/admin/check/active", name="Activate")
     */
    public function changeActive(EntityManagerInterface $em,Request $request)
    {

        $id = $request->get('id');
        $User = $this->getDoctrine()->getRepository(User::class)->find($id);
        if ($User->getActivateUser()){
            $User->setActivateUser(false);
        }else {
            $User->setActivateUser(true);
        }
        $em->persist($User);
        $em->flush();
        return new \Symfony\Component\HttpFoundation\Response(
            json_encode($User->getActivateUser())
        );
    }
    /**
     * @Route("/admin/check/Wintermembership", name="WinterMember")
     */
    public function changeWinterMember(EntityManagerInterface $em,Request $request)
    {

        $id = $request->get('id');
        $User = $this->getDoctrine()->getRepository(User::class)->find($id);
        if ($User->getWinterMember()){
            $User->setWinterMember(false);
        }else {
            $User->setWinterMember(true);
        }
        $em->persist($User);
        $em->flush();
        return new \Symfony\Component\HttpFoundation\Response(
            json_encode($User->getWinterMember())
        );
    }

    /**
     * @Route("/admin/check/Summermembership", name="SummerMember")
     */
    public function changeSummerMember(EntityManagerInterface $em,Request $request)
    {

        $id = $request->get('id');
        $User = $this->getDoctrine()->getRepository(User::class)->find($id);
        if ($User->getSummerMember()){
            $User->setSummerMember(false);
        }else {
            $User->setSummerMember(true);
        }
        $em->persist($User);
        $em->flush();
        return new \Symfony\Component\HttpFoundation\Response(
            json_encode($User->getSummerMember())
        );
    }
}
